### PR TITLE
Content from old site #

### PR DESCRIPTION
**Pull request by korolr**

### CODE REVIEW

**Comment by squiddy** [comment]
Please rebase on current source branch. I already picked one part of your changes.

In the future, please separate your changes into more commits, makes it easier to pick changes. Because I don't think I'm going to merge this as it is.

**Comment by squiddy** [comment]
It would be good if you could announce your plans beforehand. That way no work is done needlessly.

**Comment by korolr** [comment]
Good

**Comment by LinuxDonald** [comment]
@korolr are you working on an new pr?

**Pull request closed without merging**
